spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: qwer
    url: jdbc:mysql://localhost:3304/test?serverTimezone=Asia/Seoul
    hikari:
      maximum-pool-size: 5 # 최대 pool 크기
      connection-timeout: 30_000 # 30s
      keepalive-time: 300_000 # 5m
      validation-timeout: 5_000 # 5s
      max-lifetime: 1_800_000 # 30m
      leak-detection-threshold: 60_000 # 누수 판별 기준값
      pool-name: db-pool
      data-source-properties:
        socketTimeout: 3000
        cachePrepStmts: true
        prepStmtCacheSize: 250
        prepStmtCacheSqlLimit: 2048
        useServerPrepStmts: true
        useLocalSessionState: true
        rewriteBatchedStatements: true
        cacheResultSetMetadata: true
        cacheServerConfiguration: true
        elideSetAutoCommits: true
        maintainTimeStats: false
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties: # ⭐ 이게 빠졌어요!
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect  # 여기로 이동!
        format_sql: true  # 추가 권장